version: 2
updates:
  # Maintain dependencies for the root directory (dev scripts usually)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for the Server
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for the Collector
  - package-ecosystem: "npm"
    directory: "/collector"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for the Frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for the Embed Widget
  - package-ecosystem: "npm"
    directory: "/embed"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for the Browser Extension
  - package-ecosystem: "npm"
    directory: "/browser-extension"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain Dockerfile dependencies
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
